---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

# Configuration per https://pre-commit.ci/#configuration
ci:
  autoupdate_schedule: monthly
  skip: [no-commit-to-branch]
  autoupdate_commit_msg: 'ci(pre-commit.ci): pre-commit autoupdate'
