---
logger:
  logs:
    qmc5883l: INFO
number:
  - id: !remove ${prefix_id}temperature_offset
sensor:
  - id: !extend ${prefix_id}qmc5883l_id
    platform: qmc5883l
    address: 0x2C
    temperature: !remove ${prefix_id}qmc5883l_temperature
